name: UploadCV
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install deps
      run: |
        sudo pip install pelican[markdown]
    
    - name: Build Site
      run: pelican content -o output -s pelicanconf.py
